@baseUrl = http://localhost:3001

### hae kaikki henkilöt
GET {{baseUrl}}/api/persons

### tarkista info-sivu
GET {{baseUrl}}/info

### lisää testihenkilö ja tallenna vastaus myöhempiä pyyntöjä varten
# @name createPerson
POST {{baseUrl}}/api/persons
Content-Type: application/json

{
  "name": "rest client test",
  "number": "040-1234567"
}

### hae juuri lisätty henkilö
GET {{baseUrl}}/api/persons/{{createPerson.response.body.id}}

### päivitä juuri lisätyn henkilön numero
PUT {{baseUrl}}/api/persons/{{createPerson.response.body.id}}
Content-Type: application/json

{
  "name": "rest client test",
  "number": "040-7654321"
}

### testaa liian lyhyt nimi
POST {{baseUrl}}/api/persons
Content-Type: application/json

{
  "name": "ab",
  "number": "040-1234567"
}

### testaa vääränmuotoinen numero
POST {{baseUrl}}/api/persons
Content-Type: application/json

{
  "name": "invalid number test",
  "number": "12345678"
}

### poista juuri lisätty henkilö
DELETE {{baseUrl}}/api/persons/{{createPerson.response.body.id}}

### testaa virheellinen mongo id
GET {{baseUrl}}/api/persons/not-an-id

### testaa tuntematon osoite
GET {{baseUrl}}/api/unknown
